ECR_REPO_NAME: dev
  IMAGE_TAG: ${{ github.run_number}}


jobs:
  build:
    runs-on: ubuntu-latest  # guthub runner
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: Aws creds config 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}     # OIDC
          aws-region: ${{ env.AWS_REGION}}
