name: Resume ci Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with tag
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest 
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Login to Docker hub
      run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
    - name: Tag image 
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: Push Image 
      run: docker push  ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}

  deploy: 
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.237.143.9
          username: ${{ec2-user}}
          key: ${{vars.KEY}}
          script: |
              docker stop resume || echo ""
              docker rm resume || echo ""
              docker pull ec2-user/my-image-name:${{ github.run_number}}
              docker run -d docker --name resume -p 8080:5001 ec2-user/my-image-name:${{github.run_number}}

              